### ISSUE TITLE
Support progressive JPEG

### ISSUE THREAD

**Issue by nstoddard** [PistonDevelopers/image#114]
Currently, this library doesn't support progressive JPEG images, which are very common and are the default output format for some programs, such as GIMP.

**Comment by Ralle** [comment]
+1, I need SOF2 support in JPEG files. I am trying to write a converter for BLP (Warcraft 3) to JPG. It apparently uses JPEGs with SOF2.

**Comment by kaksmet** [comment]
Fixed by #513
