### ISSUE TITLE
Encode/decode DXT compressed textures

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/image#127]
@dobkeratops Since you requested it the comment on Reddit http://www.reddit.com/r/rust/comments/2kp1di/presenting_rustimage_v01/clni7ci , would you care to elaborate on resources required to implement this?

**Comment by sp-1234** [comment]
>Does the patent status prevent us simply writing an encoder/decode and distributing that on github?

there's no need to write decoder, it's done entirely by hardware.

**Comment by CensoredUsername** [comment]
As the patents have expired DXT support has been merged.
