### ISSUE TITLE
Quality control jpeg

### ISSUE THREAD

**Issue by brycefisher** [PistonDevelopers/image#177]
Maybe I missed this in the readme or examples, but I'm nit seeing a way to control the quality of jpegs encoded using this library. Is that implemented?

**Comment by nwin** [comment]
Encoding JPEGs is non-trivial and should be left to specialized libraries. I.e. mozjpeg. Closing for now.

**Comment by brycefisher** [comment]
:+1: thanks for the explanation and totally agree
