### ISSUE TITLE
Update to 1.0.0-alpha

### ISSUE THREAD

**Issue by brookst** [PistonDevelopers/image#233]
I've made a few updates for Rust 1.0.0-alpha on https://github.com/brookst/image/compare/update-nightly 
I haven't finished updating everything as I'm stuck on errors of the form:

    error: mismatched types: expected `&mut color::Rgb<T>`, found `&_` (values differ in mutability)

Hopefully I'll solve those and submit a PR but I'm submitting my changes so far in case someone else wants to work on this.

**Comment by bvssvni** [comment]
I think the error is because `let &Foo(_) = x;` should be changed to `let &mut Foo(_) = x;` when `x` is mutable.

**Comment by brookst** [comment]
Ah, correct. That fixed it but @jameson-ernst beat me to it. Good to know how to fix up my own code though, thanks.

**Comment by tomaka** [comment]
Can we publish this on crates.io?
