### ISSUE TITLE
Use associated types, remove old_orphan_check

### ISSUE THREAD

**Issue by ruud-v-a** [PistonDevelopers/image#240]
Many type parameters — for example `T` on `Pixel<T>`, should actually be associated types. I suspect that it will fix the `old_orphan_check` warnings when implemented.

I am working on this, see https://github.com/ruud-v-a/image/tree/assoc-types.

**Comment by nwin** [comment]
It should probably be an associated type but as I understand the rules Pixel<T> should work since we defined it.

I wonder if the compiler to be smart enough to infer the correct buffer type if we remove the type parameter from Pixel?

**Comment by ruud-v-a** [comment]
What I have so far:

- `trait Pixel<T: Primitive> { ... }` becomes `trait Pixel { type Subpixel: Primitive; ... }`. The implementation determines the subpixel type. For example, `Luma<T>` will always have subpixel type `T`. Removing the type parameter reduces the number of type parameters considerably.
- `struct ImageBuffer<Container, T, PixelType>` becomes `struct ImageBuffer<P: Pixel, Container>`, but all impls require that at least `Container: ArrayLike<P::Subpixel>`. There is no need to have separate type params for the pixel and subpixel type, because the pixel type now determines the subpixel type. The `P` parameter _is_ required, even though it is not used in the struct itself; it is a marker type that allows `ImageBuffer<Luma<u8>, Vec<u8>>` to be distinct from `ImageBuffer<Rgb<u8>, Vec<u8>>`.
  
  This change unfortunately makes it impossible to have `&'static Any` as pixel type (because `Any` does not implement `Pixel`), and so the `into_dynamic` method cannot be expressed.

I encountered some peculiar errors, e.g. “`GreyImage` has no method `into_vec`”; it appears that the impl for `ImageBuffer<P, Vec<P::Subpixel>>` is not recognised. The `into_vec` method offers no more functionality than `into_raw` though, so `into_raw` could be used instead. I don’t know how this impacts the other functions though.
