### ISSUE TITLE
Use `perf`/SystemTap`/DTrace with `stackvis` to find performance bottlenecks

### ISSUE THREAD

**Issue by hauleth** [PistonDevelopers/image#248]
Example:
![flame graph for `fractal` example](https://cloud.githubusercontent.com/assets/291639/5801569/e660251c-9fec-11e4-9b14-b669c7235f4c.png)

It will help with looking for code that need optimization and it works like charm with `perf`. I haven't checked it against `stap` or `dtrace` but it should work also.

For now I found that decompression implementation is major bottleneck and need rewrite or maybe we should think about using external libs for image loading.

**Comment by hauleth** [comment]
Linked with #99

**Comment by nwin** [comment]
I think there is a general agreement that our inflate implementation is slow, but we do not have any replacement yet, see also #223.

**Comment by nwin** [comment]
Closing in favor of #257. I referenced it such that this information can be found.
