### ISSUE TITLE
Missing documentation in `math::utils`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/image#251]

**Comment by hauleth** [comment]
I'll do it. Now I'm trying to rewrite JPEG decoder (or using libjpeg-turbo/mozjpeg)

**Comment by bvssvni** [comment]
@hauleth You can assign issues to yourself to let people know you are working on it.

**Comment by hauleth** [comment]
I have forgotten about that.

**Comment by hauleth** [comment]
Done by 52fe43246575732cc42ba8aa66e2ab1faaab179a
