### ISSUE TITLE
std::any::TypeId moved to std::intrinsics::TypeId

### ISSUE THREAD

**Issue by thelostt** [PistonDevelopers/image#256]
When I tried to build, this error came out:

    src/buffer.rs:2:22: 2:28 error: unresolved import `std::any::TypeId`. There is no `TypeId` in `std::any` src/buffer.rs:2 use std::any::{ Any, TypeId };

I checked the rust doc, and found [this](http://doc.rust-lang.org/1.0.0-alpha/std/intrinsics/struct.TypeId.html).

So, I hope you guys fix it.

**Comment by toqueteos** [comment]
Update to latest nightlies.

**Comment by thelostt** [comment]
I've sure my rust is updated.

    rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)

**Comment by tomaka** [comment]
`2015-01-08`, that's two weeks ago

**Comment by thelostt** [comment]
Okay, I updated here and works fine.

**Comment by hauleth** [comment]
Closing.
