### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by Ralle** [PistonDevelopers/image#281]
I  wanted to test out this image crate but it did not work. This is what I am getting:

    ~/Dropbox/Rust/rustyspoon (master)$ cargo build
       Compiling log v0.2.2
       Compiling libc v0.1.1
       Compiling rustc-serialize v0.2.12
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.2.2/src/lib.rs:192:20: 192:25 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.2.2/src/lib.rs:192 #[derive(Copy, Eq, Debug)]
                                                                                                             ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.2.2/src/lib.rs:307:20: 307:25 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.2.2/src/lib.rs:307 #[derive(Copy, Eq, Debug)]
                                                                                                             ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.2.2/src/lib.rs:463:23: 463:28 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.2.2/src/lib.rs:463 #[derive(Copy, Clone, Debug)]
                                                                                                                ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.2.2/src/lib.rs:550:10: 550:15 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.2.2/src/lib.rs:550 #[derive(Debug)]
                                                                                                   ^~~~~
    error: aborting due to 4 previous errors
    Build failed, waiting for other jobs to finish...
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:259:40: 259:45 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:259 #[derive(Clone, PartialEq, PartialOrd, Debug)]
                                                                                                                                               ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:301:34: 301:39 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:301 #[derive(Clone, Copy, PartialEq, Debug)]
                                                                                                                                         ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:311:28: 311:33 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:311 #[derive(Clone, PartialEq, Debug)]
                                                                                                                                   ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:320:16: 320:21 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:320 #[derive(Copy, Debug)]
                                                                                                                       ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:1145:28: 1145:33 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:1145 #[derive(PartialEq, Clone, Debug)]
                                                                                                                                    ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:1160:21: 1160:26 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:1160 #[derive(PartialEq, Debug)]
                                                                                                                             ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:1189:28: 1189:33 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:1189 #[derive(PartialEq, Clone, Debug)]
                                                                                                                                    ^~~~~
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:1197:28: 1197:33 error: unknown `derive` trait: `Debug`
    /Users/ralle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.12/src/json.rs:1197 #[derive(PartialEq, Clone, Debug)]
                                                                                                                                    ^~~~~
    error: aborting due to 8 previous errors
    Could not compile `log`.

I am running the following version

    rustc 1.0.0-alpha (44a287e6e 2015-01-08 17:03:40 -0800)

**Comment by nwin** [comment]
Your version of Rust is too old.

**Comment by Ralle** [comment]
That's ridiculous. It's the only one they bundle up in an installer (for Mac) on the site.

Everything is chaotic right now, so I understand. I will see if I can install a more recent version seeing as mine is A MONTH OLD :D.

Thanks for the extremely quick answer.

**Comment by TyOverby** [comment]
@Ralle: there are nightly builds for every OS right here: http://www.rust-lang.org/install.html

**Comment by Ralle** [comment]
Oh. I must have clicked the wrong download link then. Thank you very much for getting me further in my project :)
