### ISSUE TITLE
Can' build with rustc 2015-02-13 21:15:39

### ISSUE THREAD

**Issue by NobbZ** [PistonDevelopers/image#295]
Hi there! When trying to compile I get the following compiler panic:

```plain
   Compiling image v0.2.0-alpha.10 (https://github.com/pistondevelopers/image#ffbd2d5e)
/home/nmelzer/.cargo/git/checkouts/image-f4d4ca6613133df7/master/src/imageops/colorops.rs:62:46: 62:66 error: internal compiler error: coherence failed to report ambiguity: cannot locate the impl of the trait `traits::Num` for the type `<<I as image::GenericImage>::Pixel as buffer::Pixel>::Subpixel`
/home/nmelzer/.cargo/git/checkouts/image-f4d4ca6613133df7/master/src/imageops/colorops.rs:62     let max: <I::Pixel as Pixel>::Subpixel = Primitive::max_value();
                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:129
```

Please take a look over it, if you can fix it on your end, or if you have to report it to rusts bugtracker.

**Comment by Potpourri** [comment]
This is a known issue:
rust-lang/rust#21756

**Comment by NobbZ** [comment]
So until this is fixed, I can't use piston? Or is there some workaround? Just tried the getting-started…

**Comment by bvssvni** [comment]
Can we keep issues like these open? It makes it easier for people to see if there are others with similar problems.

**Comment by bvssvni** [comment]
Can this be fixed with a type alias or `Primitive::max_value::<T>()`? Or is it a deeper bug connected with associated types?

**Comment by Potpourri** [comment]
@Nobbz No its unfixed, its bug in rustc, not sure we worth to seek workaround.
You can use previos nightly, in `rustc 1.0.0-nightly (3ef8ff1f8 2015-02-12 00:38:24 +0000)` works as well.

**Comment by NobbZ** [comment]
How can I retrieve an old version of rust?

2015-02-14 17:33 GMT+01:00 Nikita Belyakov <notifications@github.com>:

**Comment by Potpourri** [comment]
[Here](http://static.rust-lang.org/dist/2015-02-12/index.html)
rust-nightly-XXX, `XXX` its your tatget triple, if you windows, then `rust-mingw-nightly-XXX`
Unpack archive and run install.sh

**Comment by nwin** [comment]
The link you can find by clicking on other downloads and the on archive.

**Comment by jpernst** [comment]
What I'm curious about is if this bug is rejecting a valid design, or if it's a bug in how the compiler handles coherence failures that already existed. I'm still a little fuzzy on where the trait coherence story landed and what exactly is and isn't legal. Can anyone who has a clearer picture of the current trait coherence rules weigh in?

**Comment by simnalamburt** [comment]
:+1:

**Comment by tomaka** [comment]
> Can anyone who has a clearer picture of the current trait coherence rules weigh in?

I don't think anyone outside of the core team has a clear picture of the trait coherence rules.

**Comment by nwin** [comment]
As far as I understand it, our code should be correct. We define and implement this trait. But who knows…
