### ISSUE TITLE
Unknown filter type

### ISSUE THREAD

**Issue by OneSadCookie** [PistonDevelopers/image#299]
This image fails to load with "Unknown filter type.":

Other libraries including Apple's and stb_image handle the file fine.

![metal](https://cloud.githubusercontent.com/assets/37714/6219815/476cd6d6-b693-11e4-8dd0-e8a1097d763a.png)

**Comment by nwin** [comment]
I cannot reproduce this error.

**Comment by OneSadCookie** [comment]
I wonder what I'm doing dumb :)
