### ISSUE TITLE
Unknown filter type

### ISSUE THREAD

**Issue by OneSadCookie** [PistonDevelopers/image#300]
OK, I figured out what I was doing dumb in the previous bug report, and it was that I just gave the wrong image :p I can reproduce the "unknown filter type" error with this png:

![metalfloor](https://cloud.githubusercontent.com/assets/37714/6236555/59318584-b750-11e4-952a-75e231deca65.png)

and this code:

    fn main() {
        let image_path = Path::new("/path/to/MetalFloor.png");
        let image = image::open(&image_path).unwrap();
    }

(on 64-bit OS X)

**Comment by nwin** [comment]
Re-enconding helps. Obscure bug, my first guess would be a bug in the inflater but I have no clue…

**Comment by nwin** [comment]
Bug is somewhere in the inflater…

**Comment by OneSadCookie** [comment]
I see you closed #376 as a dup.  Whether or not the cause is similar to this one, #376 was introduced later — when I reported this one, the images that fail in #376 still loaded fine.

**Comment by nwin** [comment]
Closed via #418.
