### ISSUE TITLE
How do you change a pixel?

### ISSUE THREAD

**Issue by quadrupleslap** [PistonDevelopers/image#304]
Probably the wrong place to ask this, but how do I change a pixel to full transparency?

I can make a transparent pixel (`image::Rgba([0, 0, 0, 0]);`), but whenever I try setting it (`img.put_pixel(x, y, tranparent_pixel);`), I can't, because rust-image expects a trait I can't even use:
```rust
 expected `<GenericImage as image::image::GenericImage>::Pixel`,
    found `image::color::Rgba<_>`
(expected associated type,
    found struct `image::color::Rgba`) [E0308]
```

**Comment by nwin** [comment]
The right place to ask and continue this discussion would be http://www.reddit.com/r/rust_gamedev/ 

In any case please post a complete minimal examples that compiles that reproduces the error next time. As it is now I can just speculate that you have to convert the image to rgba first by using `to_rgba` or ˚convert' depending on the context.

**Comment by quadrupleslap** [comment]
Thanks! =)
