### ISSUE TITLE
Filter regression in PNG encoding

### ISSUE THREAD

**Issue by mbrubeck** [PistonDevelopers/image#305]
#298 created a regression that causes some images to be encoded incorrectly as PNG.  This following test case demonstrates the problem.  The PPM file is correct, but every other row of the PNG file is incorrect.

```rust
let white = image::Pixel::from_channels(255,255,255,255);
let black = image::Pixel::from_channels(0,0,0,255);
let img = image::ImageRgba8(image::ImageBuffer::from_fn(100, 100, move |x, y| {
    if (x + y) % 2 == 0 { white } else { black }
}));
img.save(&mut File::create(&Path::new("test.png")).unwrap(), image::PNG);
img.save(&mut File::create(&Path::new("test.ppm")).unwrap(), image::PPM);
```

Reverting #298 fixes the bug.

Looking at that patch, I think that [this line](https://github.com/PistonDevelopers/image/commit/e01fecbf75eff4a8939e68c49abfb6ab7ed7bce4#diff-e1a0e41840ecaefa415299d6f179b679R90) and [this line](https://github.com/PistonDevelopers/image/commit/e01fecbf75eff4a8939e68c49abfb6ab7ed7bce4#diff-e1a0e41840ecaefa415299d6f179b679R99) are incorrect, since `current[i - bpp]` is not the same as `orig[i - bpp]` in the previous code; it is a value that may have been changed by the preceding `for` loop.

**Comment by mbrubeck** [comment]
Another problem is that [this code](https://github.com/PistonDevelopers/image/commit/e01fecbf75eff4a8939e68c49abfb6ab7ed7bce4#diff-e1a0e41840ecaefa415299d6f179b679R89) uses `-1` as an unsigned integer literal, so `range_step_inclusive` tries to step by `usize::MAX` and stops immediately due to overflow.

**Comment by mbrubeck** [comment]
The issue in the previous comment could have been prevented by rust-lang/rust#5477.

**Comment by nwin** [comment]
Thanks. Good findings!
