### ISSUE TITLE
Improve build times.

### ISSUE THREAD

**Issue by csherratt** [PistonDevelopers/image#311]
I was wondering if there was any ideas on how the build times could be improved for this crate. It currently takes about a 1minute to compiler for a none release build.

Some ideas:
- Move the image codecs into sub crates
- Add `feature` flags to disable codecs that are not used

**Comment by TyOverby** [comment]
I really like this idea.  You could have the default feature include ever codec, but if I have a crate that only uses PNG and JPEG, then I could just select those.

**Comment by nwin** [comment]
Good idea. I woud prefer feature flags. I don’t want to maintain 6 crates on crates.io

**Comment by bvssvni** [comment]
The problem with feature flag is they only allow one feature set at a time, which must be named. Example https://github.com/bvssvni/start_piston/blob/master/Cargo.toml#L90-L98

**Comment by bvssvni** [comment]
We can use a "only_jpeg_png" feature flag and leave out the other codecs when this is enabled.

**Comment by tomaka** [comment]
No, please.

Let's say you have library A which depends on `image` *without* `only_jpeg_png`, and library B which depends on `image` *with* `only_jpeg_png`.

If you try to use both A and B at the same time, Cargo will compile `image` with `only_jpeg_png` as it assumes that features are only beneficial. And tadaa, library A won't work.

**Comment by bvssvni** [comment]
We could move codecs into smaller crates, and make them depend on this library.

In the long term this is a better solution. We should figure out a way to make working with crates.io a less burden on the maintainers.

**Comment by csherratt** [comment]
When I tried to at least add a feature flag I ran into problems with [dynimage.rs](https://github.com/PistonDevelopers/image/blob/8501481b3f51e3a720be3302f684fe4811e365c9/src/dynimage.rs#L567). You can use a feature flag to remove enums, but table entries is not possible.

**Comment by bvssvni** [comment]
Also, see https://github.com/rust-lang/cargo/issues/1169 If Cargo get this, then working with multiple crates could be easier.

**Comment by bvssvni** [comment]
It seems that multiple features are supported, there is a bug in the command line, but works in Cargo.toml. I opened https://github.com/rust-lang/cargo/issues/1378

**Comment by hauleth** [comment]
IMHO the best way to improve compilation times (and improve implementation of new formats) is to split format encoders and decoders to separate crates (possibly in the same repo) and compile them only when needed. Just add "meta crate" that will contain common traits.

**Comment by nwin** [comment]
The build times really degraded. Since we did not change much it must be partially a rustc thing…

**Comment by nwin** [comment]
A month ago a release build took 1 minute (30s for image crate) on my computer. Now it is 2. From this two minutes time takes 1:30. That means the build times of image trippelt.

**Comment by nwin** [comment]
Ok, I think it wasn’t our fault that the compile times exploded: https://github.com/rust-lang/rust/issues/25069
