### ISSUE TITLE
Fork master to an "old_io" branch

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/image#333]
The transition the new io is expected to be a such big change that we might want to use the old io on a separate branch. People can put a `branch = "old_io"` in the Cargo.toml.

**Comment by nwin** [comment]
Good idea. we should do that as soon as new_io lands

**Comment by bvssvni** [comment]
It seems most of it is stabilized now http://doc.rust-lang.org/std/io/index.html

**Comment by bvssvni** [comment]
Confirmed on IRC: new_io has landed.

I'll create a "old_io" branch.
