### ISSUE TITLE
Add some more owners to crates.io

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/image#335]
The response of uploading a new version to crates.io just recently is a bit slow, and it would be nice if this was a few hours at most. Any volunteers? Objections?

**Comment by agmcleod** [comment]
:+1:

**Comment by bvssvni** [comment]
I've added @tomaka as owner.

**Comment by hauleth** [comment]
Big :+1:

**Comment by nwin** [comment]
(y)
