### ISSUE TITLE
ImageEnd reading many PNGs

### ISSUE THREAD

**Issue by OneSadCookie** [PistonDevelopers/image#376]
Attached image and 29 other PNGs in my project fail to load with

     "image 0.3.6 (git+https://github.com/PistonDevelopers/image)"

though they previously loaded with

    "image 0.2.0-alpha.10 (git+https://github.com/PistonDevelopers/image)"

They fail with `ImageEnd` on OS X (Yosemite, 10.10.3 beta)

    rustc --version
    rustc 1.0.0-nightly (f207ecbe0 2015-04-03) (built 2015-04-03)

![characterwalking1](https://cloud.githubusercontent.com/assets/37714/6996035/cd21161c-dbc2-11e4-81b5-6e808e6ee4bf.png)

**Comment by OneSadCookie** [comment]
(reencoding the files with Preview's "Export" allows them to load correctly, too)

**Comment by nwin** [comment]
I convinced myself that this has the same cause as #300. Closing as duplicate.
