### ISSUE TITLE
ImageError does not impl std::error::Error

### ISSUE THREAD

**Issue by jpernst** [PistonDevelopers/image#388]
This is causing a bit of friction as I try to integrate `image` into my project. It seems that it isn't possible to implement it for `ImageError` currently since it does not own the error string and thus cannot lend it. Taking `std::io` as an example, a good approach for this might be to change `ImageError` to `ImageErrorKind` and then create a new `ImageError` opaque struct that can contain the kind and the error message.

Unfortunately, this does mean an API change, so I didn't want to just start doing it without knowing if the change would be acceptable or not.

**Comment by nwin** [comment]
It is possible to implement `Error` with the current enum.

**Comment by nwin** [comment]
done
