### ISSUE TITLE
How create indexed image?

### ISSUE THREAD

**Issue by BratSinot** [PistonDevelopers/image#389]
I found function "image::imageops::colorops::dither", what convert pixel colors, but image still RGB. "image::imageops::colorops::index_colors" return indexes, not image. So how create custom image with palette?

**Comment by nwin** [comment]
There is no generic interface yet to make use of these functions. But you can simply save the image as GIF (paletted PNG is not supported yet), that will reduce the image to 256 colors.

**Comment by Hugo-Trentesaux** [comment]
So there is no way of creating PNG with indexed color profile?

Example of use case: https://zola.discourse.group/t/image-processing-using-indexed-colors-profiles/499/3

**Comment by fintelia** [comment]
I believe that the PNG crate supports it now (see [Encoder::set_palette](https://docs.rs/png/0.16.7/png/struct.Encoder.html#method.set_palette)), but there aren't plans to expose that functionality in this higher level crate.

**Comment by HeroicKatora** [comment]
I would recommend opening a new issue, for example to discuss a potential interface for this. For comparison `gif` is essentially always an indexed color profile and, as fintelia mentioned, `png` does support it so I wouldn't rule out adding support for it in some way. Posting on a closed issue from 5 years ago will not be very helpful, a lot of things have change and only maintainers and the original posters get notified..
