### ISSUE TITLE
Add compression to PNG

### ISSUE THREAD

**Issue by nwin** [PistonDevelopers/image#390]
The ability to compress PNG images was reduced in order to make it work with Rust 1.0 beta that should be added back at some point…

**Comment by tomaka** [comment]
Shouldn't the zlib/deflate encoder/decoder be extracted into its own library?

**Comment by nwin** [comment]
That would be the optimal solution. I just put this up to document it somewhere else than in some PR comments.

**Comment by nwin** [comment]
I wonder if we shouldn’t just use flate2 for compression and decompression…

**Comment by tomaka** [comment]
:'(

**Comment by nwin** [comment]
I would be very happy keep the pure Rust solution. But writing a zlib en-/decoder is hard work. I tried both ours, the one form #99 and the one from alexcrichton/rust-compress. They all have bugs. If we are lucky they are easy to fix. I didn’t succeed.

**Comment by tomaka** [comment]
I don't think it's *that* hard to write.

**Comment by kvark** [comment]
@nwin fixing rust-compress would be nice, if it's failing. We need to add your case as a test.

**Comment by nwin** [comment]
@tomaka not hard but tedious
@kvark I will try to extract some stream, I can’t remember which images failed it. My guess was that something is fishy about the static Huffman tables. The current testcases of rust-compress are all using dynamic Huffman tables. I tried to make a testcase with zlib but that passed…

**Comment by nwin** [comment]
Closing in favor of #419.
