### ISSUE TITLE
20 second hang time when loading image files.

### ISSUE THREAD

**Issue by ecogiko** [PistonDevelopers/image#399]
Hello,

When building rust source code for the first time after a change (dependencies have already been compiled) I usually have to wait 20 seconds which are due to a call to image::load(). I am not sure why that is, I tried asking in the rust IRC but I got no response.

    ico@arch test $ time cargo build --verbose
           Fresh rustc-serialize v0.3.14
           Fresh byteorder v0.3.9
           Fresh libc v0.1.6
           Fresh rand v0.3.8
           Fresh num v0.1.24
           Fresh enum_primitive v0.0.1
       Compiling test v0.1.0 (file:///home/ico/Code/Projects/test)
         Running `rustc src/main.rs --crate-name test --crate-type bin -g --out-dir /home/ico/Code/Projects/test/target/debug --emit=dep-info,link -L dependency=/home/ico/Code/Projects/test/target/debug -L dependency=/home/ico/Code/Projects/test/target/debug/deps --extern image=/home/ico/Code/Projects/test/target/debug/deps/libimage-9da13252c48f4989.rlib`
           Fresh image v0.3.8

    real    0m19.991s
    user    0m19.673s
    sys 0m0.243s
    ico@arch test $

I am using multirust and here are my toolchain versions:

    multirust: beta revision:

    rustc 1.0.0-beta.4 (850151a75 2015-04-30) (built 2015-04-30)
    cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)

    multirust: nightly revision:

    rustc 1.1.0-nightly (c42c1e7a6 2015-05-02) (built 2015-05-02)
    cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-05-01)

The source code that hangs for 20 seconds is this: 

	extern crate image;
	
	use std::io::Cursor;
	
	fn main() {
	    let _ = image::load(Cursor::new(&include_bytes!("../opengl.png")[..]), image::PNG);
	}

The image file is 600x279px and changing formats around didn't do anything.

Here is my system information:
        
    Linux arch 4.0.1-1-ARCH 1 SMP PREEMPT Wed Apr 29 12:00:26 CEST 2015 x86_64 GNU/Linux

I don't know how to test this more. Any help?

**Comment by TyOverby** [comment]
It looks like you are timing the build step, not the actual image loading.

**Comment by ecogiko** [comment]
Using the image library like so takes the time to normal (~5 seconds)

    [dependencies.image]
    git = "https://github.com/PistonDevelopers/image"
    default-features = false
    features = ["png"]

**Comment by nwin** [comment]
as @TyOverby already said you are benchmarking the actual build time. I suppose you observe this behavior because you’re pasting the image data directly into the source code (with `include_bytes!`).
