### ISSUE TITLE
Again: using crates for the decoders

### ISSUE THREAD

**Issue by nwin** [PistonDevelopers/image#400]
I’m getting more and more the impression that it would be best to split image into standalone crates. Maybe it would be the best option to keep them in the same repository anyway? What’s your opinion?

I’m currently experimenting with replacements for the [gif](https://github.com/nwin/gif) and [png](https://github.com/nwin/png) de-/encoder (mainly to support streaming of content) and am quite happy with having these two guys as separate crates…

**Comment by TyOverby** [comment]
I originally was on the side of using cargo features, but now I'm leaning this way.  

Seeing as we can put as many crates in the same cargo package, we should keep them all in the same repository, and in the same cargo `image` package.

**Comment by kvark** [comment]
I might be missing something trivial, but there should be some code that selects the decoder based on the image format. How would this code know about external crates?

**Comment by nwin** [comment]
By using features as we do already.

**Comment by kvark** [comment]
@nwin ok, so what's the benefit you expect from having the decoder sub-crates?

**Comment by bvssvni** [comment]
What about a small crate for the core and some sub crates, and then reexport all of them in an "image" crate?

**Comment by TyOverby** [comment]
I think having `image`, `image-png (etc)` and `image-all` is more intuitive than `image-core`, `image-png`, and `image`.

**Comment by ruud-v-a** [comment]
I am in favour of separate crates for the formats. Decoding and image processing are different things, it makes sense to separate them. It also makes sense to have a wrapper that just loads an image regardless of its format. In my opinion `image` depending on `image-png`, …, depending on `image-core` would be more intuitive. It has the advantage that it does not break anything for users of the `image` crate.

I wonder though, would it be possible to avoid `image-core` entirely? If you only use `image-png`, then for example the `ImageDecoder` trait is rather useless, the impl could be provided by `image`. There would be some duplication, but on the other hand it would make the encoders/decoders more useful in their own right.

**Comment by nwin** [comment]
I think a high-level `ImageDecoder` should just be implemented in `image`. The different formats are so different that you need a custom de-/encoder type for every format anyway…

**Comment by ruud-v-a** [comment]
Yes, that is what I meant.

**Comment by bvssvni** [comment]
@nwin Are you working on this now?

**Comment by nwin** [comment]
Not right now. I wanted to start when I get my new png decoder to work (where I'm almost done beside some edge cases)
