### ISSUE TITLE
Problem with GIF transparency

### ISSUE THREAD

**Issue by kmcallister** [PistonDevelopers/image#401]
[This GIF](https://github.com/servo/servo/blob/master/tests/ref/alpha_gif_a.gif) should be transparent on the bottom half, but the library decodes it entirely as opaque pixels:

```
00000000  00 00 ff ff 00 00 ff ff  00 00 ff ff 00 00 ff ff  |................|
*
00040000
```

**Comment by nwin** [comment]
Thanks for reporting. That affected all transparent gifs.
