### ISSUE TITLE
Incorrect decoding of paletted PNG

### ISSUE THREAD

**Issue by kmcallister** [PistonDevelopers/image#403]
[This PNG](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/images/green.png) should be solid green but the library decodes a 4-pixel stripe of black on the left edge. RGB data:

```
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 ff 00 00
00000010  ff 00 00 ff 00 00 ff 00  00 ff 00 00 ff 00 00 ff
...
```

**Comment by nwin** [comment]
Thanks you, fixed and waiting for travis…
