### ISSUE TITLE
Update the byetorder crate to 0.3.8 or later (currently 0.3.9)

### ISSUE THREAD

**Issue by madeso** [PistonDevelopers/image#406]
My travis build is failing to build byteorder 0.3.7 for rust nighly, and it seems that this is fixed in 0.3.8+.

The relevant byteorder fix:
https://github.com/BurntSushi/byteorder/commit/b8d12248946fcac08239373551fc48abe72b9ace

My travis build, that's compiling fine on beta2 but not on nightly:
https://travis-ci.org/madeso/rust-game-engine/builds/61722932

The dependency chain from me to byteorder is:
glium(any version)->image(any version)->byteorder(0.3.7)

**Comment by nwin** [comment]
Must be some caching issue, we’re not even depending on 0.3.7. cargo should just download the newest version…

**Comment by madeso** [comment]
I'm not 100 on the semver syntax, but if you're not dependening on the version, shouldn't the dependency be 0.3 or ^0.3.7?

http://doc.rust-lang.org/semver/semver/index.html#requirements

**Comment by nwin** [comment]
This is not how cargo works. Dunno if that is a bug or not.

**Comment by madeso** [comment]
That's at least what the documenation on both crates.io and rust-lang says. Then again the documentation might not be updated.

http://doc.crates.io/crates-io.html#using-crates.io-based-crates
