### ISSUE TITLE
load_rect panicks 'assertion failed: dst.len() >= len_src'

### ISSUE THREAD

**Issue by nadirs** [PistonDevelopers/image#422]
When trying to `load_rect` on a png decoder the call to `copy_memory` panicks with the aforementioned assertion failure. This is the complete error message:

    thread '<main>' panicked at 'assertion failed: dst.len() >= len_src', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.3.10/./src/lib.rs:137

It seems `load_rect` is not calculating the correct size for either the destination or the source?

**Comment by nwin** [comment]
`load_rect` will go away in it’s current form as not every image format is organized in scanlines. You can use `ImageBuffer::sub_image` instead.

**Comment by nadirs** [comment]
Ok, sadly, if I try to manipulate png files using `image::open` the PNG is corrupted (I can see it by inspecting the `sub_image`'s `pixels`).
Otherwise, how do I get an `ImageBuffer` from a `PNGDecoder`? (as it hopefully will decode the PNG correctly)

**Comment by nwin** [comment]
I don’t understand what you mean. image::open is using the PNGDecoder.

**Comment by nadirs** [comment]
Oh, I see, I didn't know it. Then I don't have other ways to get this to work. I'll see if I can figure out why the image comes out as corrupted.
Thanks for the feedback anyway!

**Comment by nadirs** [comment]
I just wanted to update this issue by saying the PNG decoder works perfectly and the "pixel corruption" was my fault. I'm going ahead and closing the issue.
Thanks for your work everyone.
