### ISSUE TITLE
Add support for 16 bit GrayScale TIFF

### ISSUE THREAD

**Issue by performance** [PistonDevelopers/image#426]
It would be nice if support to read and write 16 bit GrayScale TIFFs is added.

**Comment by nwin** [comment]
There is already read support for 16bit TIFFs but there is no support for writing any TIFF format.

**Comment by performance** [comment]
nwin, I have been trying since last week, It cannot read a 16 bit GrayScale TIFF.

**Comment by nwin** [comment]
Ah right, I'm just guessing what you did. You need to read them using the `TiffDecoder` directly. If it still does not work, please file a bug report including the error message, minimal code sample, and if possible the file in question.

**Comment by pedrocr** [comment]
I'd like to propose a better API to handle this. For most uses you want one of two things:

* An sRGB image that you will display on screen or send to another bit of code that only cares about image display
* A linear buffer to be used for further processing in your own specialized code

So the best way to handle this would be to have two methods:

* to_rgb() will always return an 8bit sRGB image that can just be displayed directly. If the source image is 16bit it gets gamma applied and 8bit converted. Image viewers will just use this and see all formats magically supported.
* to_linear() will always return an f32 linear image with values between 0 and 1. 16bit images will just be converted to f32 in that range, 8bit images will do that but with gamma unapplied. Image processors will just use this and also have all formats supported without special casing each type of image.

Would that kind of API be accepted as a PR?

**Comment by nwin** [comment]
Sounds sensible except I would scale 16bit image to `1.0`. Im currently working on a new image buffer library which provides some abstractions for exactly these uses cases (https://github.com/PistonDevelopers/image_buffer). I would prefer PR to it first instead of changing the API here.

**Comment by pedrocr** [comment]
When I say "16bit images will just be converted to f32 in that range" I mean turn ```0..65535``` into ```0.0..1.0```. Is that what you mean?
