### ISSUE TITLE
Size of a resized (down) image is higher than original

### ISSUE THREAD

**Issue by ollie** [PistonDevelopers/image#428]
Hello,

When I resize a PNG image down, the file size goes up considerably. Am I missing something in the code below? (Using image v0.3.11)

```rust
// main.rs
extern crate image;

use std::fs::File;
use std::path::Path;

use image::{
    GenericImage,
    imageops,
};

fn main() {
    let img             = image::open(&Path::new("test.png")).unwrap();
    let (width, height) = img.dimensions();
    let nwidth          = width / 2;
    let ratio           = nwidth as f64 / width as f64;
    let nheight         = (height as f64 * ratio).round() as u32;
    let resized_img     = img.resize(nwidth, nheight, imageops::Nearest);
    let ref mut fout    = File::create(&Path::new("test-resized.png")).unwrap();
    let _               = resized_img.save(fout, image::PNG).unwrap();
}
```

I am using this image https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png which goes from 218 KB to 480 KB after resize.

I can't wrap my head around this.
Thanks. :-)

**Comment by nwin** [comment]
The image is currently saved uncompressed. This is fixed in `master`. I should release a new version soon.

**Comment by ollie** [comment]
Thanks, you guys are the best. :-)
