### ISSUE TITLE
Panic in JPEG decoding of large image: arithmetic operation overflowed

### ISSUE THREAD

**Issue by twoodford** [PistonDevelopers/image#434]
I get `thread '<main>' panicked at 'arithmetic operation overflowed', src/jpeg/decoder.rs:208` when loading the following image:

![20150728_0006](https://cloud.githubusercontent.com/assets/2175841/9151761/a09eaed4-3ddc-11e5-838e-2bf115b24c46.jpg)

Smaller images don't crash here.  It looks like `mcucount` needs to be a `u32` for images above 4194304 pixels.

**Comment by nwin** [comment]
yes, that is correct
