### ISSUE TITLE
Way to compare pixel color values?

### ISSUE THREAD

**Issue by killercup** [PistonDevelopers/image#440]
I'm trying to compare the values of pixels/subpixel to specific color values. For a toy examples I want to collect a set of vibrant colors in an image.

My code looks something like this:

```rust
pub fn new<I: GenericImage>(image: I) -> Vibrancy {
    let important_pixels = image.pixels()
        .map(|(_, _, pixel)| pixel.to_rgba())
        .filter(|rgba| {
            let alpha = rgba[3];
            alpha >= 125
        })
        .map(|px| px.to_rgb())
        .collect();

    // unimplemented
    Vibrancy { pixels: vec![] }
}
```

Sadly, the comparison is not possible, because:

```text
 expected `<<I as image::image::GenericImage>::Pixel as image::buffer::Pixel>::Subpixel`,
    found `_`
(expected associated type,
    found integral variable) [E0308]
```

**Comment by nwin** [comment]
This is not a help forum, please ask this on reddit or the IRC channel. 

To make your code work you'll probably need to make some restrictions to the associated subpixel type (::SubPixel=u8) or so…

**Comment by killercup** [comment]
Thanks so much for your reply. I'm sorry for spamming your issue tracker! (I was in a hurry and this ticket was more the result of brain-dump at first convenient and relevant place I could find :smile:)

FTR, I got it working by restricting the subpixel type like you said:

```rust
where P: Sized + Pixel<Subpixel = u8>,
      G: Sized + GenericImage<Pixel = P>
```
