### ISSUE TITLE
Library scope

### ISSUE THREAD

**Issue by theotherphil** [PistonDevelopers/image#448]
I'm not sure if this is really an "issue", but I couldn't see anywhere else to discuss it. 

I want to write some toy computer vision applications in Rust, so need a bit of standard image processing functionality, e.g. histogram equalisation, contrast stretching, edge detection and HSL support. 

I plan on implementing the features I mentioned, but is this library a sensible place for them? They don't really have anything to do with supporting game engines, and this crate bills itself as being for "image encoding and decoding", with a few basic image manipulation functions thrown in.  I'm happy to maintain my own crate that just depends on this one for image loading, but it also seems silly to have lots of people reinventing the wheel  and this library appears to be the place people start when they need to do some image processing.

(I also want to implement some basic image features - HOG, SIFT, binary patterns, but these seem more obviously to not belong here!)

**Comment by nwin** [comment]
It would make sense to put it into a new crate and let image depend on it. Maybe even under the piston umbrella. @bvssvni what do you think?

**Comment by bvssvni** [comment]
Expanding the image processing features would be great, but I'm not sure that it is a good idea to put it here.

Maybe we could move the processing features out of image and to the new library?

@theotherphil I've added you to the Admin group, so you can create new repos. Once you have created one, I will add labels.

Maybe it would be an idea to start the new library, work on it for a bit, and then make a decision.

**Comment by theotherphil** [comment]
Ok, thank. I've created imageproc. Piston seems to be a pretty broad net, but if you think that this isn't really covered then I won't be offended if you remove the repo!

**Comment by bvssvni** [comment]
Nice, I added labels and the teams to [imageproc](https://github.com/pistondevelopers/imageproc). When publishing to crates.io, please add me as an owner, and I'll add some more people plus the PistonDevelopers team.
