### ISSUE TITLE
Example of sobel operator?

### ISSUE THREAD

**Issue by brycefisher** [PistonDevelopers/image#449]
I'm trying to figure how to do some kind of edge detection using this library. It feels like all the right components are here, but I keep getting stuck.

The problem I'm encountering is that I need a grayscale image to use the sobel operator on. Using the image::load() method, I get a DynamicImage which always has u8 grayscale pixels. However, u8's in Rust don't implement a square root function which I need to convolve the image using my x and y kernels. I feel like I'm doing something wrong.

Could someone point me in the right direction here? Thanks!

Here's what I've written so far (doesn't compile): https://gist.github.com/brycefisher/80ab4fe33e2775e05283

**Comment by theotherphil** [comment]
You could cast to a floating point type and then clip back after computing the gradient intensity. If you restrict your function to GrayImage inputs then you won't have to worry about how to convert arbitrary Subpixels to floats. Just in case you hadn't noticed, the filter3x3 function lets you do the actual convolving just by writing your kernel coefficients. I'm on a slightly broken phone atm so I'll add more this evening if this isn't clear and no one else has answered in the meantime. I was planning on adding this functionality to the imageproc library very shortly anyway, so you could also wait a day or two for that, or (even better) add your code when you've got it working.

**Comment by brycefisher** [comment]
:+1: That's really helpful! I'll keep trying to play with my code as a learning exercise (which is the mostly the point anyway), but I'm looking forward to seeing your sobel operator!
