### ISSUE TITLE
Support non-standard pixel types like Apple's BGRA

### ISSUE THREAD

**Issue by alexchandel** [PistonDevelopers/image#451]
Apple (and possibly Windows' GDI) use a non-standard pixel format internally, [BGRA](http://iphonedevelopment.blogspot.com/2008/10/iphone-optimized-pngs.html). This means that all image buffers that come out of `CGDisplayCreateImage` / `CGImageGetDataProvider` / `CGImageGetDataProvider` / Apple's graphics APIs have the B and R pixel swapped. It would be very convenient to be able to tell `image` that a raw buffer is BGRA, rather than having to swap them manually. The information could also be stored, and used to avoid more byte-swapping, in case the Image is saved to a format that also uses BGR.

Edit: this format is commonly called [ARGB](https://en.wikipedia.org/wiki/RGBA_color_space#ARGB).
Edit 2: confusingly, OpenGL refers to this as [BGRA](https://en.wikipedia.org/wiki/RGBA_color_space#RGBA_byte_order). In any case, we should support it.

**Comment by nwin** [comment]
I agree, we should add this as a new `ColorType`. Probably one should also add a conversion from `RGBA` to `BGRA` and vice versa via the `FromColor` trait.

**Comment by nwin** [comment]
You can have a look at the incomplete https://github.com/PistonDevelopers/image_buffer crate. Contribution and suggestion would be very welcome.

**Comment by quadrupleslap** [comment]
@Drakulix - No, the alpha channel is still at the end. Apple uses *little-endian* ARGB, which essentially BGRA, which is just RGBA with the R and the B bytes swapped.

**Comment by fintelia** [comment]
Fixed by #808
