### ISSUE TITLE
ConvertBuffer trait is private

### ISSUE THREAD

**Issue by xanium4332** [PistonDevelopers/image#452]
The issue is an inconsistency and/or missing feature. As per the documentation an implementation of the `ConvertBuffer` trait exists for `ImageBuffer` ([see bottom of docs page](http://docs.piston.rs/piston_window/image/struct.ImageBuffer.html#method.convert)). However, attempting to use the `convert()` method fails due to the trait being marked private.

> src/lib.rs:3:5: 3:33 error: trait `ConvertBuffer` is private
> src/lib.rs:3 use image::buffer::ConvertBuffer;
>                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/lib.rs:6:2: 6:19 error: source trait is private
> src/lib.rs:6 	old_img.convert()

Either the documentation should omit mentioning the existence of the `convert()` method (as it cannot be used), or the `ConvertBuffer` trait should be made public.

If this method is not meant be used, then I cannot currently see a way to convert between `ImageBuffer`s (e.g. `Rgb<u8> -> Rgba<u8>`), which would seem like a missing feature.

**Comment by nwin** [comment]
Tanks for reporting tis issue.

Its a combination of a bug in rustdoc (for displaying te private trait) and an ommited export. Te trait sould of course be public.

(seems like my keyboard lost some letters :( )

**Comment by xanium4332** [comment]
I've submitted a one-line fix PR for this. `rustc` still provides incorrect help information if you attempt to use the method without `use`ing the trait. Specifically, `rustc` recommends `use`ing the trait from its private location (rather than publicly re-exported location). However, I believe this to be a `rustc` deficiency.

**Comment by nwin** [comment]
Fixed by #453.
