### ISSUE TITLE
Broken image test case

### ISSUE THREAD

**Issue by TyOverby** [PistonDevelopers/image#454]
When attempting to load this image, I get the error: 

```
ImageError(FormatError("invalid uncompressed block len"))
```

Oddly enough, this used to work several months ago.

![test](https://cloud.githubusercontent.com/assets/573215/10420211/14b47384-7042-11e5-801d-804da7b4cbe6.png)

**Comment by nwin** [comment]
Could possibly be a duplicate of https://github.com/PistonDevelopers/image-png/issues/4. We also got a new decoder a few monts ago.

**Comment by bvssvni** [comment]
Fixed by https://github.com/PistonDevelopers/inflate/pull/2. Reopen if still a problem.
