### ISSUE TITLE
Image fails to re-encode 

### ISSUE THREAD

**Issue by nathanaeljones** [PistonDevelopers/image#459]
Re-encoding this as a jpeg causes a panic. Re-encoding it as a png causes visual artifacts. 

![test copy](https://cloud.githubusercontent.com/assets/107935/10555524/6305a2b0-743e-11e5-91f6-a0a032b8cafd.jpg)

	dimensions (50, 50)
    RGB(8)
    thread 'test::test_convert' panicked at 'shift operation overflowed',     /Users/nathanael/.cargo/registry/src/github.com-0a35038f75765ae4/image-0.3.11/./src/jpeg/encoder.rs:267

![test copy](https://cloud.githubusercontent.com/assets/107935/10555559/f1297ff8-743e-11e5-9911-5fe5c5bde018.png)

Code straight out of Readme:

      // Use the open function to load an image from a Path.
    // ```open``` returns a dynamic image.
    let img = image::open(&Path::new("test.jpg")).unwrap();

    // The dimensions method returns the images width and height
    println!("dimensions {:?}", img.dimensions());

    // The color method returns the image's ColorType
    println!("{:?}", img.color());

    let ref mut fout = File::create(&Path::new("test2.jpg")).unwrap();

    // Write the contents of this image to the Writer in PNG format.
    let _ = img.save(fout, image::JPEG).unwrap();

**Comment by nathanaeljones** [comment]
Perhaps related to https://github.com/PistonDevelopers/image/issues/431

**Comment by philipc** [comment]
Fixed by #513
