### ISSUE TITLE
Working with large images and memory

### ISSUE THREAD

**Issue by pix64** [PistonDevelopers/image#462]
Currently the image decoders will decode the entire image and store the entire result vector in memory.

For large images this will eat up a lot of RAM potentially causing a Out of Memory panic. There should be a trait method to decode up to a certain buffer size so you can then process the those pixels (display pixels on screen, convert to another format, etc) and then move on with the rest of the image.

There is a read_scanline ImageDecoder trait function (which isn't implemented for all formats), but an entire line may be too much in cases of low memory devices.

**Comment by nwin** [comment]
I brought this topic up a few times. It's not a trivial task. You'll probably need to restructure some decoders. On top of that with a few formats that is not even possible (tiled TIFF, PNG and BMP) as they depend on one or more previous lines being present. 

I think it should be up to the individual decoders to expose a memory saving interface that is best suited for the underlying format. `read_scanline` should go away.

**Comment by fintelia** [comment]
As of PR #819, there is now `ImageDecoder::into_reader` and `ImageDecoderExt::load_rect` methods that allows incremental loading of images (which falls back to loading the entire image on formats that don't support that)
