### ISSUE TITLE
Panic while decoding favicon

### ISSUE THREAD

**Issue by paulrouget** [PistonDevelopers/image#463]
```
$ cargo run --example opening ./favicon.ico
thread '<main>' panicked at 'arithmetic operation overflowed', src/ico/decoder.rs:81
```

Using this file: https://news.ycombinator.com/favicon.ico

**Comment by paulrouget** [comment]
Casting real_width/height to u32 appears to fix this issue. But I'm not sure this is the right approach.

**Comment by waddlesplash** [comment]
#464 was merged, this is now fixed.

**Comment by bvssvni** [comment]
Thanks @waddlesplash !
