### ISSUE TITLE
Host docs on docs.piston.rs

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/image#491]
Other projects uses a script to upload docs to the docs repo. Currently this repo seems to use the gh-pages branch.

**Comment by nwin** [comment]
We should use https for this script. As let’s encrypt is now running it shouldn’t be a problem to get a certificate.

**Comment by bvssvni** [comment]
https://letsencrypt.org/

**Comment by fintelia** [comment]
docs.rs/image probably makes this unnecessary
