### ISSUE TITLE
Type annotations required when creating ImageBuffer 

### ISSUE THREAD

**Issue by franleplant** [PistonDevelopers/image#494]
Hi!
    I'm kind of new with Rust so bare with me :)

Im getting this error:

```sh
src/main.rs:70:22: 70:45 error: type annotations required: cannot resolve `<_ as image::buffer::Pixel>::Subpixel == _` [E0284]
src/main.rs:70     let mut imgbuf = image::ImageBuffer::new(width as u32, height as u32);
```

I tried specializing with the `Rgba` pixel type like this:

```rs
 let mut imgbuf = image::ImageBuffer::new<image::Rgba>(width as u32, height as u32);
```

but it didnt work.

Any ideas?

Thanks a lot!
Fran

**Comment by ruud-v-a** [comment]
Try

```rust
let mut imgbuf: image::ImageBuffer<image::Rgba<u8>, _> = image::ImageBuffer::new(width as u32, height as u32);
```

instead.

```rust
let mut imgbuf: image::RgbaImage = image::ImageBuffer::new(width as u32, height as u32);
```

is an alias for that.

**Comment by franleplant** [comment]
Thanks! It worked!

**Comment by franleplant** [comment]
Here, Ill give you this present for your help (I've done it with this lib
![example1](https://cloud.githubusercontent.com/assets/1852455/11645409/06d1534a-9d33-11e5-921e-f9bc4592c53e.png)
)
