### ISSUE TITLE
Will more specialized image algorithms eventually be supported?

### ISSUE THREAD

**Issue by nicokoch** [PistonDevelopers/image#511]
I was asking myself if more specialized algorithms like canny edge detection are planned for this library (essentially making this an opencv replacement over time if you think this further) or if the focus will be on just encoding and decoding?

**Comment by bvssvni** [comment]
You might want to take a look at https://github.com/pistondevelopers/imageproc.

**Comment by nicokoch** [comment]
Thanks, exactly what I was looking for
