### ISSUE TITLE
failed to decode huffman code

### ISSUE THREAD

**Issue by Coohack** [PistonDevelopers/image#516]
please help:
on ubuntu 15.10, rust 1.7.0
panicked at 'called `Result::unwrap()` on an `Err` value: FormatError("failed to decode huffman code")', ../src/libcore/result.rs:688

this error happen with one jpg, but other jpg worked!

**Comment by kaksmet** [comment]
Can you upload the image that fails to decode somewhere and link it here please?

**Comment by Coohack** [comment]
[http://imagesite.ezhijie.net/image/devel/cf1ffefc-32cf-4280-8a20-6d8f77adc893](url)

**Comment by kaksmet** [comment]
I can't seem to reproduce this using the link you provided.

**Comment by kaksmet** [comment]
I just fixed a bug in the JPEG decoder which might have been the cause of this error.
Could you try running `cargo update -p jpeg-decoder` and see if it still fails?

**Comment by Coohack** [comment]
thanks a lot!
