### ISSUE TITLE
Support SVG

### ISSUE THREAD

**Issue by zmoshansky** [PistonDevelopers/image#524]
This would be fantastic to round out the very commonly used formats. More specifically, just loading and displaying an SVG would be very useful.

It's scalable nature makes it well suited for icons as a better alternative to PNG/GIF/WEBP(Exciting to see WEBP support!) for GUI's.

**Comment by pix64** [comment]
This library is really focused on raster graphics formats. The API doesn't really lend itself well to vector images. You throw an image at it and it decodes it to an array of RGB bytes. Each time you wanted to render your vector image at a different resolution you would have to completely reparse the svg file from scratch.

**Comment by zmoshansky** [comment]
Hmm, I was worried that that was the issue at hand. I've added information below for posterity, closing as it seems out of scope for this project... Perhaps another Piston library.

I'm actually having a tough time finding references to rasterizing SVG to RGBA in rust. I assume the rendered RGBA could then just be stuffed into an ImageBuffer and used easily within Piston.

It looks like the options (at time of writing) are to use another library and try to render it right to an openGL context, use an external library to rasterize a png/webp (ex. imagemagick), or tie into cairo/rsvg/etc and try getting RGBA pixel data out.

https://www.reddit.com/r/rust/comments/2haxdb/vector_graphics_in_rust/
https://developer.gnome.org/rsvg/
