### ISSUE TITLE
Add alpha support for bmp decoder

### ISSUE THREAD

**Issue by philipc** [PistonDevelopers/image#539]
The bmp decoder can read rgba32 images, but currently it discards the alpha information when we're not reading an ico file.

**Comment by philipc** [comment]
@pix64 I'm mostly finished adding alpha support for bitfield bitmaps. (Note that this isn't for RGB32 bitmaps, for which we are correctly ignoring the "alpha" information.) However, after implementing this support, the reference tests for V3_A1_R5_G5_B5.bmp and V3_A4_R4_G4_B4.bmp are failing. This is because these images do contain alpha information (the alpha mask is non-zero), but we were ignoring it. The issue is that the alpha field is set to 0 in all of the pixels for these images, which is a bit weird. If I open these images in gimp, it also thinks that the pixels are all transparent. Can you remember how these images were generated? I just want to make sure there isn't something wrong with my understanding of these images.

**Comment by pix64** [comment]
They were created with Photoshop. Windows and Photoshop both thinks all the pixels are opaque.

**Comment by philipc** [comment]
Ah okay, they're more likely to be right. Do you know of any documentation on the V3 header?

**Comment by pix64** [comment]
Upon further inspection photoshop does realize there is an alpha channel it just doesn't associate it with transparency. When I created the image the default alpha channel all black (zeros).

**Comment by philipc** [comment]
The reason I created this issue is because http://entropymine.com/jason/bmpsuite/bmpsuite/html/bmpsuite.html has a bunch of images with alpha channels, and claims that these should be displayed as transparency. Both firefox and gimp treat them as transparency, but Microsoft Edge ignores the alpha channel for all of these images. Any opinion on how we should treat it? My feeling is we should read the alpha channel since it is there, and it would be up to the caller to discard the alpha channel if needed.

**Comment by pix64** [comment]
I think that is a reasonable approach.
