### ISSUE TITLE
fractal example is broken

### ISSUE THREAD

**Issue by stan4cb** [PistonDevelopers/image#553]
let mut imgbuf = image::ImageBuffer::new(imgx, imgy);

type annotations required: cannot resolve `<_ as image::Pixel>::Subpixel == _` [E0284]
rustc 1.11.0-nightly (bb4a79b08 2016-06-15)

**Comment by nwin** [comment]
Works fine here. Did you modify the example?

```
$ cargo build --example fractal
$ rustc --version
rustc 1.11.0-nightly (bb4a79b08 2016-06-15)
```

**Comment by stan4cb** [comment]
hmm, i've and it seems the problem was missing
`let _ = image::ImageLuma8(imgbuf).save(fout, image::PNG);`
line
