### ISSUE TITLE
Please support resize with height or width omitted

### ISSUE THREAD

**Issue by joshtriplett** [PistonDevelopers/image#556]
`DynamicImage::resize` takes a width and height, and resizes preserving aspect ratio.  However, sometimes the operation you want is "make the image this wide" or "make the image this tall", without caring about the other dimension other than preserving aspect ratio.  Rather than calculate this by hand, I'd like to have a resize method that takes two `Option<u32>` arguments for the sizes, which would allow calls like `.resize(Some(80), None, ...)` to say "make this 80 pixels wide and whatever height would preserve the aspect ratio".

**Comment by philipc** [comment]
Can you already achieve that by specifying `u32::MAX` for the dimension you don't care about? I think the idea of the current `resize` is that you specify a bounding box, and it scales the image to fit within that box.

**Comment by joshtriplett** [comment]
@philipc The exact semantic of `resize` wasn't entirely obvious at a glance. Would you consider documenting the "bounding box" behavior in the documentation for `resize`? That would address this bug without needing to add a new function.

**Comment by philipc** [comment]
Yes, I think that should be documented. The current description for `nwidth` and `nheight` is incorrect.
