### ISSUE TITLE
How to get an RGB String?

### ISSUE THREAD

**Issue by flosse** [PistonDevelopers/image#563]
It should be easy to get s.th. like `"#aa00cc"` but I wasn't able to do it.

`pixel.to_rgb().to_string()`  doesn't work of course so how can I access the raw values to construct the string myself?
I thought it could work like this:
```rust
let rgb = pixel.to_rgb().channels();
let r: u8 = rgb[0];
let g: u8 = rgb[1];
let b: u8 = rgb[2];
```
But this doesn't work: `expected type 'u8'` ... `found type '<P as image::Pixel>::Subpixel'`.
So how can I get the value of a `Subpixel`?

**Comment by nwin** [comment]
Looks like there is missing some context such that rustc is not able to determine that `Subpixel` is an `u8`. Probably it wouldn’t be to stupid to have an `as_hex()` convenience method for rgb.

Please note, that this is not a help forum.
