### ISSUE TITLE
Make a transparent image?

### ISSUE THREAD

**Issue by sector-f** [PistonDevelopers/image#578]
I'm trying to open an image, make it partially transparent, and then copy it to a solid background.

I'm loading the image using `load_from_memory`, which gets me a `DynamicImage` (of the `ImageRgb8` variant, as far as I can tell). I'm getting a solid image with `ImageBuffer::from_pixel`, and then making a `DynamicImage` from that.

Here's how I'm trying to make the image transparent:

````rust
if let Some(alpha) = bg.alpha {
    image = DynamicImage::ImageRgba8(image.to_rgba());
    for pixel in image.as_mut_rgba8().unwrap().pixels_mut() {
        pixel.apply_with_alpha(
            (|i| i),
            (|_| alpha),
        );
    }
}
````

So, here are some of the problems I'm having:

1. I don't know the difference between `apply_with_alpha` and `map_with_alpha`. The docs aren't very clear
2. The closures need to return a u8, but I'm not sure about what's done with them. Does this value become the new value of the that channel? Are the two values multiplied? I can only guess

Edit: 

Now trying 

````rust
image = DynamicImage::ImageRgba8(image.to_rgba());
if let Some(alpha) = bg.alpha {
    for pixel in image.as_mut_rgba8().unwrap().pixels_mut() {
        pixel[3] = (alpha as f32 * 255f32) as u8;
    }
}
````

This seems to be working partially, but the image isn't being blended with the background. Rather, it seems to be replacing the section of the image that it's copied to.

**Comment by nwin** [comment]
Regarding the difference between `map` and `apply`, the docs are pretty clear. `apply` works in-place while `map` produces a copy. Have a look at the signature. Regarding the blending, probably you want to use `blend`?
