### ISSUE TITLE
Expose quality/compression controls when saving as JPG

### ISSUE THREAD

**Issue by agersant** [PistonDevelopers/image#581]
When saving images as JPG, it would be useful for users to decide how much they want the image to be compressed.

**Comment by teovoinea** [comment]
I'd like to take this on.

I found `new_with_quality` in https://github.com/PistonDevelopers/image/blob/019e2a4f856b73f66c4540e27a8930ae20996509/src/jpeg/encoder.rs#L299

And the save function in https://github.com/PistonDevelopers/image/blob/019e2a4f856b73f66c4540e27a8930ae20996509/src/dynimage.rs#L361

Would adding an `Option<u8>` to the `save` signature in `dynimage.rs` be ok?
