### ISSUE TITLE
Empty PNG causes panic

### ISSUE THREAD

**Issue by sunjay** [PistonDevelopers/image#593]
Trying to save an empty PNG (with dimensions 0x0) causes a panic:

```
thread 'main' panicked at 'assertion failed: size != 0', ../src/libcore/slice.rs:256
```

Saving an empty jpg does not result in any panic. An empty .jpg is saved with no problems.

This should probably be a `Result::Err()` instead since `save()` returns a `Result` anyway.

**Comment by nwin** [comment]
Indeed, thank you. Tracking as https://github.com/PistonDevelopers/image-png/issues/43.
