### ISSUE TITLE
Need cheap way to convert between DynamicImage formats

### ISSUE THREAD

**Issue by sunjay** [PistonDevelopers/image#597]
When opening a JPEG, you get a different DynamicImage enum variant than when you open a PNG. We need some cheap way to convert between the enum variants without copying too much memory. Using `to_rgba()` is really slow. A `into_rgba()` method would be great where it consumes the current dynamic image and returns the new format.

**Comment by nwin** [comment]
I doubt that there is a cheap way. How do you come to the claim that an `into_rgba` would be much faster? As `Rgba` is bigger than any other variant one needs to reallocate anyway. I'm not arguing that `into_rgba` wouldn't be a good addition, but the speed gain, if any, will be much smaller than you think.

**Comment by sunjay** [comment]
Darn. Sorry, I was more asking than implying it could be. I know RGBA is bigger, but is there any way to consume an RGB image and do minimal allocations while ending up with an RGBA image?

**Comment by nwin** [comment]
One could directly unpack into a rgba sized buffer but this probably optimizing on the wrong point. That would be only on excess allocation & copy per image. There probably lower hanging fruits available.

**Comment by sunjay** [comment]
I see what you mean. We can open this up again if anyone finds a need for it. 

Thanks
