### ISSUE TITLE
Publish 0.12.1 for byteorder 1.0.0

### ISSUE THREAD

**Issue by nox** [PistonDevelopers/image#609]

**Comment by oyvindln** [comment]
This might want to wait for https://github.com/PistonDevelopers/image-png/issues/51 too.

**Comment by nox** [comment]
@oyvindln What wants to wait? We can do as many bumps as we want, no? :)

**Comment by nwin** [comment]
I wonder if we should change our dependencies to caret requirements, thus using png="^0.6" such that we don’t have to bump image for every little bugfix in the dependencies. Do you see any drawback from this?

**Comment by nwin** [comment]
Ok, I got it wrong, that should already be the case.
