### ISSUE TITLE
How do I change color of pixel?

### ISSUE THREAD

**Issue by NathHorrigan** [PistonDevelopers/image#633]
As title suggests...

**Comment by hako** [comment]
@NathHorrigan Take a look at [`put_pixel`](https://docs.rs/image/0.12.3/image/trait.GenericImage.html#tymethod.put_pixel).

Example:
```rust
img.put_pixel(x, y, image::Rgba([255u8, 255u8, 255u8, 255u8]));
```
This should set the pixel at `(x,y)` to white.

**Comment by NathHorrigan** [comment]
@hako - Thanks worked, I figured it was put_pixel but coudn't figure out how the Rgba worked
Thanks!!

**Comment by vitvakatu** [comment]
Solved
