### ISSUE TITLE
Upscaling with linear interpolation doesn't give expected result

### ISSUE THREAD

**Issue by lukors** [PistonDevelopers/image#650]
Using the `image::FilterType::Triangle` filter seems to give incorrect results. I'm assuming that a triangle filter is the same thing as what other software usually calls a "linear" filter, because in the documentation it says "Linear Filter" under that filter type (source: https://docs.rs/image/0.13.0/image/enum.FilterType.html ).

This is the code I run:
```
extern crate image;
use std::fs::File;
use std::path::Path;

fn main() {
    // Load image.
    let image_path = Path::new("heart.png");
    let img = image::open(&image_path).unwrap();

    // Resize image.
    let width = 1024;
    let height = 1024;
    let filter = image::FilterType::Triangle;
    let img = img.resize_exact(width, height, filter);

    // Write image.
    let output_path = Path::new("output.png");
    let ref mut fout = File::create(&output_path).unwrap();
    let _ = img.save(fout, image::PNG).unwrap();
}
```

This is my input image:
![heart](https://cloud.githubusercontent.com/assets/1719884/26278880/32b6325a-3da5-11e7-8664-40c27dcf5e43.png)

This is the image that the program outputs:
![output](https://cloud.githubusercontent.com/assets/1719884/26278884/39e4fa84-3da5-11e7-9468-cbb1d9545ca9.png)

This is the result you get if you upscale the image in GIMP with linear interpolation:
![heart_gimp](https://cloud.githubusercontent.com/assets/1719884/26278889/54a454a0-3da5-11e7-92d4-c3f75bf11357.png)

**Comment by stevebob** [comment]
Hi. I recently opened a PR (https://github.com/PistonDevelopers/image/pull/661) to fix some issues with image scaling. I tried running your code with my changes applied to the image library:
![output](https://user-images.githubusercontent.com/417118/27767059-7b923530-5f2b-11e7-816a-ff183e9cb392.png)

**Comment by lukors** [comment]
That's awesome, excellent work!

I guess I wait for the PR to get accepted before I close this issue, right?

**Comment by stevebob** [comment]
I think so, yeh.

**Comment by lukors** [comment]
This was fixed in the latest version https://github.com/PistonDevelopers/image/pull/673
