### ISSUE TITLE
panic on simple 2x2 pixel gif

### ISSUE THREAD

**Issue by drahnr** [PistonDevelopers/image#655]
Version `0.13.0`

`panicked at 'called `Result::unwrap()` on an `Err` value: FormatError("Image truncated")'`

    #[test]
    fn it_works_for_gif() {
        let path = Path::new("tests/assets/test_image.gif");
        let img = from_path(&path);
        // there is more stuff here, but it does not matter
    }

where (the actual implementation as a little mote complicated)

```
use image::{DynamicImage, open};
pub fn from_path<P>(path: P) -> DynamicImage
        where P: AsRef<Path> {
    open(path).unwrap()
}
```

The image was created with gimp and exported as gif (I tried both, interleaved and non-interleaved, same results)
![test_image](https://cloud.githubusercontent.com/assets/667047/26834140/cdb54ec6-4ad4-11e7-98fc-16d26027c70f.gif)

**Comment by nwin** [comment]
Thanks for pointing that out, funny that I never tested it with a 2x2 image.

**Comment by drahnr** [comment]
Thanks, that was a quick fix :)
