### ISSUE TITLE
Current master (as well as the latest version from crates.io) fails during the build

### ISSUE THREAD

**Issue by application-developer-DA** [PistonDevelopers/image#656]
It seems to be some problem with dependencies.

The error message is:
```
error[E0412]: cannot find type `BigInt` in this scope
   --> /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/num-rational-0.1.37/src/lib.rs:671:30
    |
671 | impl FromPrimitive for Ratio<BigInt> {
    |                              ^^^^^^ not found in this scope

error: no associated item named `from_float` found for type `Ratio<_>` in the current scope
   --> /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/num-rational-0.1.37/src/lib.rs:681:9
    |
681 |         Ratio::from_float(n)
    |         ^^^^^^^^^^^^^^^^^

error: no associated item named `from_float` found for type `Ratio<_>` in the current scope
   --> /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/num-rational-0.1.37/src/lib.rs:685:9
    |
685 |         Ratio::from_float(n)
    |         ^^^^^^^^^^^^^^^^^
```

P.S.: The patch version for `num` has been updated today, the crate itself is compilable, so I think something is wrong with the dependencies / compatibility between `num*` crates used from `image`.

**Comment by application-developer-DA** [comment]
Ok, I think I found the issue. The problem seems to be in this file in `Cargo.toml`:

`num-rational = { version = "0.1.32", default-features = false }`

When I remove `default-features = false`, everything compiles well again. Is there really a need to keep default features disabled?

**Comment by jonas-schievink** [comment]
Looks to be https://github.com/rust-num/num/issues/297, update your lockfile

**Comment by application-developer-DA** [comment]
It is indeed that issue.
