### ISSUE TITLE
DynamicImage implementation bug of GenericImage

### ISSUE THREAD

**Issue by Rolandde** [PistonDevelopers/image#657]
I have been using this crate for only a short time, but did not find this bug posted.

The code that causes the issue is found [here](https://github.com/PistonDevelopers/image/blob/7c4450f9cc87ebad102893b2aca893b0f73cd60e/src/dynimage.rs#L425-L426).

```rust
impl GenericImage for DynamicImage {
    type Pixel = color::Rgba<u8>;
```

This approach hard codes the associated pixel type as Rgba, even though the DynamicImage holds four different pixel types. This leads to strange compilation bugs. The following compiles as it should:

```rust
let mut big = ImageBuffer::new(1000, 1000) as image::GrayImage;
let small = ImageBuffer::new(10, 10) as image::GrayImage;
big.copy_from(&small, 0, 0);
```

If you wrap small in the correct enum, the compilation fails, as copy_from now expects the pixel to be Rgba

```rust
let mut big = ImageBuffer::new(1000, 1000) as image::GrayImage;
let small = ImageBuffer::new(10, 10) as image::GrayImage;
let small_wrap = image::DynamicImage::ImageLuma8(small);
big.copy_from(&small_wrap, 0, 0);  
```

I am not experiences enough in Rust to know if the GenericImage trait can be coded with the Enum pixel variants in mind.

**Comment by nwin** [comment]
No you can’t easily, this is how DynamicImage is intended to work (`DynamicImage` distinguishes between different formats at run time while `GenericImage` and `ImageBuffer` work at compile time). You need to convert explicitly by using `to_luma`.
