### ISSUE TITLE
Add a "thumbnail" method

### ISSUE THREAD

**Issue by shssoichiro** [PistonDevelopers/image#674]
I would find it useful to have a method in `image` that takes an image and resizes to an exact width and height while preserving pixel aspect ratio by cropping any excess after resizing to achieve the desired dimensions.

**Comment by teovoinea** [comment]
I think you're looking for the [resize](https://docs.rs/image/0.17.0/image/enum.DynamicImage.html#method.resize) function.

**Comment by shssoichiro** [comment]
Not quite. If the documentation is correct, that function will ensure both
dimensions are always equal to or smaller than the target resolution. That
means if the aspect ratio doesn't match, one dimension of the image will be
smaller than I want. What I'm looking for is a function that will always
give me the exact resolution I want and preserve aspect ratio by resizing
so that one dimension is equal to the target and the other is larger, then
cropping off the sides of the larger dimension to get the exact target
resolution.
