### ISSUE TITLE
Docu outdated?

### ISSUE THREAD

**Issue by hadmut** [PistonDevelopers/image#683]
Hi, 

I'm just learning rust and how to use that image crate, not everything is obvious. 

Trying just a simple 
    let mut imgbuf = image::ImageBuffer::new(512,512);
as described in section 4.2.1 of the README.md runs into 

error[E0284]: type annotations required: cannot resolve `<_ as image::Pixel>::Subpixel == _`

(using rustc 1.17.0 and cargo 0.18.0) 

Seems as if the docu is somewhat outdated and the api has changed since, and I guess that it requires two type arguments as generics, but I don't currently see what exactly to pass. 

Please update the examples. 

regards

**Comment by Fripplebubby** [comment]
Check out https://github.com/PistonDevelopers/image/issues/494
