### ISSUE TITLE
Outdated examples in readme

### ISSUE THREAD

**Issue by leoschwarz** [PistonDevelopers/image#693]
Some of the examples in the README.md file are outdated, e.g. in section 6.1. `img.save` does only take one argument now and would not compile like that anymore.

Would it make more sense to move the examples into the examples directory, or should the ones in the README.md file just be updated? The advantage of the first course of action would be that bit rot could be prevented by running `cargo test`, however the later has the advantage of providing a quick reference which is probably the intended goal?

**Comment by bvssvni** [comment]
Just update README.md. The API is less likely to change now, so bit rot is not a big problem.
