### ISSUE TITLE
The speed of resize function is too slow

### ISSUE THREAD

**Issue by xinghun92** [PistonDevelopers/image#710]
I want to shrink my image, but the speed of resize function is too slow. I am not sure if I use this function in a wrong way. The test code goes here,
```
extern crate image;

use image::{FilterType, GenericImage};
use std::time::Instant;

fn main() {
    let bytes = ::image::open("./tests/origin.jpg").unwrap();
    let (height, width) = bytes.dimensions();

    let height = (height as f64 * 0.9) as u32;
    let width = (width as f64 * 0.9) as u32;

    let st = Instant::now();
    bytes.resize_exact(height, width, FilterType::Lanczos3);
    println!("time cost: {:?}", st.elapsed());
}
```
The time cost is about 86 seconds, And I change the FilterType to Nearest, it also cost about 21 seconds. The size of this image is 2M, and the resolution is 4032 * 3024.
My CPU is AMD Ryzen 1700, and memory is 16G.
Do I use it in a wrong way? Thanks!

**Comment by crazymykl** [comment]
Did you compile it in release mode?

**Comment by xinghun92** [comment]
I compile it with release mode, the time cost of Lanczos3 is about 12 seconds, and the time cost with other filter is less than 1 second, Thanks.
