### ISSUE TITLE
Is bit-depth limited only to 8?

### ISSUE THREAD

**Issue by dawid-s** [PistonDevelopers/image#712]
Just a question. Do I understand correctly that this project only supports 8-bit images? If I am wrong could you please let me know how I can create a 16-tiff for example? 

Thank you.

**Comment by nwin** [comment]
It also supports 16 bit images but the support is incomplete. You would have to use the TIFF decoder directly instead of using the convenience methods for opening images.

This library only supports reading tiff files so it is not possible to create any.

**Comment by dawid-s** [comment]
Thank you for the information @nwin .
