### ISSUE TITLE
Zero frames in a gif

### ISSUE THREAD

**Issue by calum** [PistonDevelopers/image#725]
Hi there,

I'm struggling to get the frames from a gif image. I've tried a couple of different gifs and they all come out as just 1 frame. Am I doing something obviously wrong?

```rust
    let mut f = File::open(filename).expect("File not found");

    let mut decoder = gif::Decoder::new(f);

    let mut frames = decoder.into_frames().expect("error decoding gif");

    for (i, frame) in frames.enumerate() {
        let mut image = frame.into_buffer();

        // display the image:
        //render_image(image.convert(), width, height);

        println!("Frame: {}", i);
        thread::sleep(time::Duration::from_millis(100));
        println!("next frame...");
    }
```

Every time I run this, I only see
```
Frame: 0
next frame...
```

Thanks for any help!

Calum

**Comment by nwin** [comment]
Indeed, outputting the frames is just not implemented.

**Comment by calum** [comment]
Since you've marked this as help wanted, could I work on it and make a pull request? I was hoping to be able to use each frame as an individual Rgbimage since I already have my own functions to display them.

I noticed you removed the easy tag
Do you anticipate this to be a hard task? I'm willing to spend time doing some background reading if necessary.

**Comment by calum** [comment]
Just to keep you updated on where I'm heading with this, I've tried to use the `decoder_to_image` function but the only issue is that I want to call it multiple times but my value is moved after the first iteration. Do you think I'm going about it right?

`gif.rs`
```rust
pub use self::gif::{Frame};
use animation::{Frame as Image_Frame, Frames as Image_Frames};
use dynimage::decoder_to_image;

...

fn is_animated(&mut self) -> ImageResult<bool> {
    Ok(true)
}

fn into_frames(self) -> ImageResult<Image_Frames> {
    let mut frames = Vec::new();
    loop {
        let image_result = decoder_to_image(self); // <-- self moved here
        match image_result {
            Ok(dynamic_image) => {
                let image = dynamic_image.to_rgba();
                frames.push(Image_Frame::new(image));
            },
            Err(_) => break
        };
    }

    Ok(Image_Frames::new(frames))
}
```

**Comment by calum** [comment]
I understand what you mean now about adding the background. I've got the function currently returning all the frames from the gif, but when I tested it on a gif file I end up with a lot of missing pixels. Presumably, these missing pixels can be taken from another frame. I'm trying to work it out.

```rust
fn into_frames(mut self) -> ImageResult<Image_Frames> {
    let mut frames = Vec::new();
    let reader = try!(self.get_reader());
    loop {
        if let None = try!(reader.next_frame_info()) {
            break;
        }
        let mut vec = vec![0; reader.buffer_size()];
        try!(reader.fill_buffer(&mut vec));
        if let Some(image_buffer) = ImageBuffer::from_raw(
            reader.width() as u32,
            reader.height() as u32,
            vec
        ) {
            let frame = Image_Frame::new(image_buffer);
            frames.push(frame);
        };
    }
    Ok(Image_Frames::new(frames))
}
```

**Comment by nwin** [comment]
You’ll need to use the gif crate directly. Have a look at at the disposal method. It determines how to handle the frames

https://docs.rs/gif/0.9.2/gif/enum.DisposalMethod.html

**Comment by calum** [comment]
Thanks for the pointer. I'm making decent progress now. Hopefully won't take much longer.

**Comment by nwin** [comment]
Can you please implement it in a way that the actual frames are produced. I.e. all the same size, with blending etc. I’m not sure but probably one should collapse frames with a delay of 0 into a single one.

**Comment by calum** [comment]
Okay, I will do. I'll be taking some holiday this weekend so will probably get it finished sometime next week.

**Comment by drozdziak1** [comment]
Hi, I'm working on a little project where I render a Mandelbrot set animation with changing parameters and I basically need the opposite of what you @calum are working on - a way to take my buffers and transform them into frames and then encode them in a GIF. **Is that possible to do yet from the `image` crate?**

**Comment by calum** [comment]
Hi @drozdziak1, I think that what you are asking for is possible. I'll assume you have an iterator over your buffers.
```rust
// create a vec of frames
let frames = Vec::new();
for buffer in buffers {
   frames.push(Frame::from_parts(buffer));
}

// encode the frames into a gif
let mut file = File::create("foo.gif")?;
let encoder = gif::Encoder::new(file);
for frame in frames {
    encoder.encode(frame);
}
```
I haven't tested this yet. There are probably loads of things wrong with my example like mutable errors and stuff but that's the rough idea.
