### ISSUE TITLE
Simple example is slow on 5.5MB file

### ISSUE THREAD

**Issue by anderspitman** [PistonDevelopers/image#745]
When running the following example on a 5.5MB 3008x4544 file:

```rust
extern crate image;

use std::fs::File;

use image::GenericImage;

fn main() {
    // Use the open function to load an image from a Path.
    // ```open``` returns a `DynamicImage` on success.
    let img = image::open("Chicken Room.jpg").unwrap();

    // The dimensions method returns the images width and height.
    println!("dimensions {:?}", img.dimensions());

    // The color method returns the image's `ColorType`.
    println!("{:?}", img.color());

    let ref mut fout = File::create("test.png").unwrap();

    // Write the contents of this image to the Writer in PNG format.
    img.save(fout, image::PNG).unwrap();
}
```

It takes 55 seconds on a 3GHz Sandy Bridge machine. A release build is much faster (1.4 seconds). These both seem high to me for reading basic data from a file and writing to another format. But I haven't worked with images much, so I wanted to check here.

If these times are normal, it seems like the best workflow for developing my code would be to use a much smaller image to get the pipeline working and then use a release build for actually converting my files?

I was hoping to host these files on a webserver that would dynamically resize them on the fly, but it seem it would be way to slow for that. Any suggestions besides just preconverting the sizes I need?

**Comment by HeroicKatora** [comment]
I suspect this to be the png encoder, the format is painful to **en**code with high performance in my experience. Can you test decoding and encoding separately? In release only, since debug builds don't provide accurate nor comparable figures.

**Comment by anderspitman** [comment]
Commenting out the encode results in 0.57 seconds.

**Comment by HeroicKatora** [comment]
Some comparison data from `convert`:

- `time convert arp299.jpg test.jpg`: 0m1,044s (where arp299 is 5760x2340, 11MB)

**Comment by anderspitman** [comment]
Sorry forgot to respond. I agree everything is within reasonable values. Thanks for your help @HeroicKatora.
