### ISSUE TITLE
Out of range panic with imageops::thumbnail

### ISSUE THREAD

**Issue by francesca64** [PistonDevelopers/image#767]
Repro: https://github.com/francesca64/thumbnail-repro

**Comment by HeroicKatora** [comment]
Thank you for the report. 

It appears to happen when the source image is smaller than the requested thumbnail. Specifically:            https://github.com/PistonDevelopers/image/blob/210c0e4d29a58026242ba796dfcd90c4cda48e3a/src/imageops/sample.rs#L307
this line shifts the sample window by one in all cases, even when `x_ratio < 1.0`. 

I'm not sure how to fix this, there a a few possibilities:
 - Upscale the image to fit the requested dimensions, with some gaussian to interpolate the missing pixels. This would correspond to the average filter applied by downscaling of thumbnails
 - Use the nearest pixel instead, that might look very suboptimal
 - Switch to something provided by `resize` only in the case of `x_ratio < 1.0` or `y_ratio < 1.0`.
 - Return an `Err` instead
 - Return a copy of the original, unmodified file (I would find this very surprising)

**Comment by francesca64** [comment]
Thanks for looking into this!

> Upscale the image to fit the requested dimensions, with some gaussian to interpolate the missing pixels. This would correspond to the average filter applied by downscaling of thumbnails

This sounds the most like what I would expect, based on the info you've given here. Either way, the most important thing to me is that the functionality is documented.

**Comment by HeroicKatora** [comment]
![Upscaled](https://i.imgur.com/4RIGNMt.png) is the upscaled thumbnail of ![Sample](https://github.com/francesca64/thumbnail-repro/raw/master/test.png)

The colours appear to be a bit darker, since we interpolate directly in RGB for better speed, but otherwise no glaringly obvious big artifacts.  Apropos, I haven't actually benchmarked the new implementation yet so it might currently be a bit slower.  I'll try to get to it if I can but if you'd be able to run some yourself (in the integrated use case) that would be swell, @francesca64 .

**Comment by francesca64** [comment]
Thanks! My use case for this was simply the `window_icon` example in winit: https://github.com/tomaka/winit/blob/master/examples/window_icon.rs#L60

This is obviously faster than Lanczos3, but I don't imagine there's anything meaningful I can say about how good the performance is upscaling to 32x32. I originally encountered this problem when working with taskbar icons (where the target size was 256x256) but that's not relevant anymore.

This doesn't produce great results when upscaling my contrived 3x3 test image to 32x32, where the white pixel ends up shifted from the center to 1/4 from the top left corner:
![test](https://user-images.githubusercontent.com/2096580/40593645-d2ab98b4-61f7-11e8-98a4-1dc9b828a88e.png)

However, I'm not sure how much that matters in practice. Either way, my real concern here was the unexpected panic, since it meant I couldn't rely on the function for my use case, so I'm happy with this fix.
