### ISSUE TITLE
Loosen version constraints on dependent crates

### ISSUE THREAD

**Issue by spearman** [PistonDevelopers/image#770]
The num crates seem to change pretty frequently, causing them to fall out of sync with other crates, and byteorder is 1.0 so pegging to a specific patch version doesn't seem necessary.

**Comment by bvssvni** [comment]
`x.y.z` is equal to `^x.y.z`, see https://github.com/steveklabnik/semver#requirements

I believe you're thinking of `=x.y.z`.

**Comment by spearman** [comment]
Oh you're right. I suppose the only exception is for 0.0.x version crates.
