### ISSUE TITLE
Readme example 6.1 behind new API

### ISSUE THREAD

**Issue by petr-tik** [PistonDevelopers/image#781]
Using image v0.19.0 and wanted to build example 6.1. cargo build gives the error below

```
error[E0061]: this function takes 1 parameter but 2 parameters were supplied
  --> src/main.rs:21:9
   |
21 |     img.save(fout, image::PNG).unwrap();
   |         ^^^^ expected 1 parameter

```

According to [current src of save function](https://github.com/PistonDevelopers/image/blob/master/src/dynimage.rs#L455-L466), the format is inferred from the name of the file

**Comment by HeroicKatora** [comment]
Thanks for the report.
@bvssvni Related to #775 , I suspect there are other examples that should receive an update as well.
