### ISSUE TITLE
Add `load_from_raw`.

### ISSUE THREAD

**Issue by c-edw** [PistonDevelopers/image#792]
I think a `load_from_raw` function would be very useful for loading unencoded image data that is already in memory, which you might get if you're creating images dynamically. I thought `ImageFormat::BMP` might have allowed me to do this, but it was looking for the BMP signature.

**Comment by c-edw** [comment]
I've just noticed that `ImageBuffer` [has a function like this](https://docs.rs/image/0.19.0/i686-apple-darwin/image/struct.ImageBuffer.html#method.from_raw), but for some it only shows up the sidebar. When I click it, nothing happens.

I had a look at the code for this function and it's not quite what I'm looking for - I need to load a DynamicImage from a raw buffer.

**Comment by HeroicKatora** [comment]
`DynamicImage` is a public enum, with the following declaration, desugaring all type aliases:

```
pub enum DynamicImage {
    ImageLuma8(ImageBuffer<Luma<u8>, Vec<u8>>;),
    ImageLumaA8(ImageBuffer<LumaA<u8>, Vec<u8>>;),
    ImageRgb8(ImageBuffer<Gray<u8>, Vec<u8>>;),
    ImageRgba8(ImageBuffer<GrayA<u8>, Vec<u8>>;),
}
```

In your use case, it should be possible to first construct the ImageBuffer with the function you found yourself and then wrap it into the applicable enum variant.
