### ISSUE TITLE
Opening a PBM file returns wrong ColorType, thus trying to .save() panics

### ISSUE THREAD

**Issue by jmaibaum** [PistonDevelopers/image#794]
Something seems to be wrong inside `PNMDecoder` (using v0.19.0 of the crate). Trying to open a PBM file, and saving it back afterwards to a new PBM file (or a PNG file, did not try other formats though) panics:

```rust
extern crate image;

use image::GenericImage;

fn main() {
    let img = image::open("test.pbm").unwrap();
    println!("{:?}", img.color());
    println!("{:?}", img.raw_pixels().len());
    println!("{:?}", img.dimensions());
    img.save("out.pbm").unwrap();
}
```

The issue seems to be that the `ColorType` is recognized as a `Gray(8)` here, instead of `Gray(1)` which would be expected from a quick glance at [src/pnm/decoder.rs](https://github.com/PistonDevelopers/image/blob/master/src/pnm/decoder.rs).

Here is the small 10px x 10px test file used (attached as a PNG, because PBM is not allowed here, should be easy enough to convert back to PBM): ![test](https://user-images.githubusercontent.com/3957164/43282174-b76d2dea-9115-11e8-8639-5c84c2d831c5.png)

**Comment by jmaibaum** [comment]
Sorry, forgot to add the output of the above test program before hitting on save:

```
Gray(8)
668
(10, 10)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: StringError("Image buffer does not correspond to size and colour") }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by HeroicKatora** [comment]
The encoder should accept both `Gray(1)` and `Gray(8)`. But more troubling to me `raw_pixels` reports with a length of 668 while I would expect 100 bytes of samples. The error originates https://github.com/PistonDevelopers/image/blob/d000240fc263fde294236ace79e1873eaa7a20ac/src/pnm/encoder.rs#L301 which ensure that the sample count is correct for width, height and colour type.

**Comment by jmaibaum** [comment]
I did not yet succeed debugging the issue further due to lldb reporting ambiguous references, which made it impossible (for me so far, since I'm new to lldb debugging) to inspect the ColorType during load.

At least from watching which match targets where hit, it seemed to me that at least during initial reading of the image data, the ColorType is correctly found to be `Gray(1)`.

So yes, there are two questions remaining:

1. When (and why) is the ColorType changed from `Gray(1)` to `Gray(8)`?
2. Why are there 668 raw pixel bytes instead of 100?

I have no prove yet, but I think that the answer to 2 is related to the answer to 1.

**Comment by philipc** [comment]
#796 has a minimal fix.

A few things to be aware of:

- [`decoder_to_image()`](https://github.com/PistonDevelopers/image/blob/d000240fc263fde294236ace79e1873eaa7a20ac/src/dynimage.rs#L546) converts `Gray(1)` to `ImageLuma8`.
- the [skip calculation](https://github.com/PistonDevelopers/image/blob/d000240fc263fde294236ace79e1873eaa7a20ac/src/dynimage.rs#L552) was wrong, which resulted in the strange length of 668. I've fixed this.
- [`PbmBit::from_bytes`](https://github.com/PistonDevelopers/image/blob/d000240fc263fde294236ace79e1873eaa7a20ac/src/pnm/decoder.rs#L575) was also converting to `Gray(8)`, which is wrong if it claims the `colortype()` is `Gray(1)`. I've fixed this.
- There's probably more colortype errors in the pnm decoder. I haven't fixed these.

**Comment by HeroicKatora** [comment]
@philipc Thank you for finding the parts i dynimage. I was not aware that dynimage could deal with colour depths not multiple of 8 values and instead wanted to convert to a more common format. Other colour types which are neither 8 nor 16 bit depth should currently fail to decode.

**Comment by jmaibaum** [comment]
I have just tested @philipc 's PR branch, and it fixes the P4 to P4 roundtrip test for me as well, so P4 decoding seems to be fine after these changes.

>  - There's probably more colortype errors in the pnm decoder. I haven't fixed these.

Unfortunately, yes. If I export the `test.png` from above to P1 (ASCII PBM) using GIMP for example, I get a

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FormatError("Error parsing sample value")', libcore/result.rs:945:5

on `let img = image::open("test.pbm").unwrap()` from both @philipc 's PR branch and the regular 0.19.0 crates.io release, but this seems to be some an other issue. Should I open a new ticket?

I didn't do too extensive further tests apart from exporting the `test.png` file to P2, P3, P5 and P6 formats as well and trying these as inputs (leaving the output to a P4 PBM), and checking if all outputs were identical.

**Comment by HeroicKatora** [comment]
Please open it as a new issue. I believe the current decoder does not yet conform to the standard (again), as `pbm` ascii is different to the other ascii encoded pnm formats in that whitespace within the pixel raster is to be discarded instead of being used as a sample value separator. I will asssign myself to that new issue and fix it asap.

**Comment by jmaibaum** [comment]
Thanks @HeroicKatora .

So, from my point of view, the root issue here has been resolved in @philipc 's PR.
