### ISSUE TITLE
Compilation to WebAssembly (question)

### ISSUE THREAD

**Issue by jumasheff** [PistonDevelopers/image#806]
Hi! Thank you for your awesome job! I am new to Rust (started reading Rustbook) and excited about WebAssembly :) Wanted to know, is it feasible to compile this lib to WebAssembly, so that we can use it in es6/js?
Currently, we have a Flash app for image editing, but it is very slow and practically unusable and I was wandering, could it be lighter/faster than that Flash app (assuming, we'll have to write a new frontend for this editing backend).

**Comment by fintelia** [comment]
Some users have reported success in compiling for WebAssembly, so I'd say it is worth giving it a shot.
