### ISSUE TITLE
ImageBuffer has wrong index calculation

### ISSUE THREAD

**Issue by HeroicKatora** [PistonDevelopers/image#836]
All buffer index calculations for accessing pixel samples in the internal buffer are done in `u32` for the most part:

https://github.com/PistonDevelopers/image/blob/50e29cda9470ddb579948c590c8b4b09e90e2863/src/buffer.rs#L375

The cast to `usize` is late in that case, it should happen before the multiplication. This leads to overflow–silent in release mode–when using a large image and large indices.

That means that for large images not all pixels are accessible, and the function `get_pixel_mut` is not injective, even for images with `width > 0 && height > 0 && P::channel_count() > 0`. See https://github.com/PistonDevelopers/imageproc/issues/281 for a scenario where that can turn out to facilitate undefined behaviour.

Also, contrary to the documentation, the function will not always panic when the indices were out of bounds of the image. Rather, it will only panic when the indices are out of bounds of the underlying buffer that might have been bigger (`ImageBuffer::from_raw`).

**Comment by HeroicKatora** [comment]
Can be both. Mostly this is changing the calculation to instead be performed in `usize` where necessary. The easiest way is to just change it to always do the calculation in `usize` but that will probably be a performance hit due to the wider multiplication type. So a comprehensive fix would first establish some benchmark to test the impact of the changes, and if the type change turns out to be an issue think of a flag or other way to have a fast-path for common image representations in which this is not an issue. Afterall, all images with a pixel could of `< u32::max_value()` will never run into this and since that is about >99% of all images in use it would be harsh to degrade their performance for such a fringe case.

**Comment by lazypassion** [comment]
how large are the images that overflow?

**Comment by HeroicKatora** [comment]
Anything that overflow `y * self.width + x` (`x`, `y`, `self.width` are all `u32`). So for example accessing the last row of a `65536 x 65537` image. Quite large, but not completely insane as defined by 'rgb8 still fits in memory'.

**Comment by fintelia** [comment]
It is worth profiling to be sure, but I strongly suspect that switching to 64-bit multiplies would not have any noticeable performance impact. The memory access alone could easily take orders of magnitude longer than the index calculation

**Comment by HeroicKatora** [comment]
Even when correctly wrapping everything in `checked_mul`? With channel counts it is not even statically guaranteed that the index fits into a `u64`.

**Comment by HeroicKatora** [comment]
It destroys benchmarks. Granted, this is a bit of an overly restrictive and paranoid [example implementation](https://github.com/HeroicKatora/image/blob/1d068f702ee51877ce945d953cb3cf8da1d4b0fb/src/buffer.rs#L373).

Before:
```
test buffer::test::bench_image_access_good_cache               ... bench:   1,541,207 ns/iter (+/- 224,258) = 1946 MB/s
```

After:
```
test buffer::test::bench_image_access_good_cache               ... bench:   3,274,975 ns/iter (+/- 88,886) = 916 MB/s
```

**Comment by fintelia** [comment]
I think it might be all the checked operations rather than the operand lengths. On my machine, this version is only one cycle slower per loop iteration than the original. (Removing the if statement brings it back to identical performance).
```rust
pub fn get_pixel(&self, x: u32, y: u32) -> &P {
    if x >= self.width || y >= self.height {
        panic!();
    }

    let no_channels = <P as Pixel>::channel_count() as usize;
    let min_index = (self.width as usize * y as usize + x as usize) * (no_channels as usize);
    <P as Pixel>::from_slice(&self.data[min_index..][..no_channels])
}
```

**Comment by fintelia** [comment]
If that multiplication overflows then [this one](https://github.com/PistonDevelopers/image/blob/50e29cda9470ddb579948c590c8b4b09e90e2863/src/buffer.rs#L606) or [this one](https://github.com/PistonDevelopers/image/blob/50e29cda9470ddb579948c590c8b4b09e90e2863/src/buffer.rs#L317) must have as well.

**Comment by HeroicKatora** [comment]
You're right. So we should probably add the `checked_mul` to those places and then use your variant. Seems good!

**Comment by HeroicKatora** [comment]
[Now](https://github.com/HeroicKatora/image/blob/index/src/buffer.rs#L374-L379) we got back almost the same performance:

```
test buffer::test::bench_image_access_good_cache               ... bench:   1,759,194 ns/iter (+/- 62,646) = 1705 MB/s
```
