### ISSUE TITLE
Would it be possible to get the channel count and colortype for the underlying pixel of an image buffer

### ISSUE THREAD

**Issue by lazypassion** [PistonDevelopers/image#842]
It would be useful to me to get the color type and channel count for an image buffer without first accessing a pixel. Would that be possible to add? Essentially adding a get_channels() function and color_type() for ImageBuffer.

**Comment by JoshLambda** [comment]
There is probably a better way to do it, but you can declare a function to access associated type `Pixel` of `ImageBuffer`.
```
fn channel_count<P: Pixel, Container: Deref<Target = [P::Subpixel]>>(
    _: &ImageBuffer<P, Container>,
) -> u8 {
    P::channel_count()
}

let image_buffer_channel_count = channel_count(&my_image_buffer);
// Then do the same for color_type()
```
