### ISSUE TITLE
How to implement a generic image transformation?

### ISSUE THREAD

**Issue by ferrouswheel** [PistonDevelopers/image#890]
I'm trying to implement a generic image transformation function, and I'm struggling a bit.

I want it to work for Rgb/Luma etc, and regardless of subpixel size. i.e. I want it to work regardless of the number of channels, and the underlying data type.

I thought I would copy the contrast function, as it's closest in signature to what I want:

https://github.com/PistonDevelopers/image/blob/master/src/imageops/colorops.rs#L53

However, I can't access `image::traits::Primitive` in my own create, so this signature won't work.

Is there a way around this or a better way for a user of the image crate to implement generic image transformations?

**Comment by birktj** [comment]
The primitive trait is public https://docs.rs/image/0.21.0/image/trait.Primitive.html, so you can use it if you want.

**Comment by ferrouswheel** [comment]
Ah, my mistake. I was stuck on version 0.20.1 - thanks!
