### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by DAddYE** [PistonDevelopers/image#99]
I know, I know, :dancer: early stage.

Although, I'm _very_ *very* interested to know how it performs with jpg (or png). 

I did some image manipulations (most resize things) in the past few days (see: https://github.com/daddye/vips) and I had to give up and use straight c with libturbojpeg.

Would be very nice to know that now is possible to use rust for that!

Anyway, not a rustler, but the code seems very clean, simple and concise. For what is worth, Congrats!

**Comment by nwin** [comment]
Closing in favor of #257.
